language: go

go:
 - "1.10.x"
 - "1.11.x"
 - "tip"

# before_install:
#  - make debs
#  - mkdir -p $TRAVIS_BUILD_DIR $GOPATH/src/github.com/theodesp
#  - test ! -d $GOPATH/src/github.com/koneko096/gojikan && mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/koneko096/gojikan || true

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

matrix:
 allow_failures:
 - go: tip

after_success:
 - bash <(curl -s https://codecov.io/bash)